#!/bin/bash -x

# création de l'AC
openssl ecparam -out c_p_ac.pem -name prime256v1 -genkey

# faire le certificat racine
#openssl req -config root-ca.cnf -x509 -sha256 -key cle_prive_acpem -text -out ca.root.cert.pem

## mot de passe 'toto' pour la clé privé
# cle privée pour la signature
#openssl ecparam -genkey -name prime256v1 | openssl ec -aes256 -out cle_privee_certifplus_signature.pem -passin pass:toto
# cle public pour la signature
﻿#openssl ec -in cle_privee_certifplus_signature.pem -pubout -out cle_publique_certifplus_signature.pem
############################################################################


#############################################################################
## faire le certificat de l'association Certifplus
# certificate pour la signature
#openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=serveur" -reqexts ext -sha256 -key cle_privee_certifplus_signature.pem  -text -out ecc.csr.pem
# signer le certificat
#openssl x509 -req -days 3650 -CA ca.root.cert.pem -CAkey cle_prive_ac.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ecc.csr.pem -text -out certificat_signature.pem
############################################################################################

# generer biclé pour le crtificat du serveur frontal
#openssl ecparam -out private_key_serveur_frontal.key.pem -name prime256v1 -genkey
