#!/bin/bash -x


## mot de passe 'toto' pour la clé privé
# generer la biclé  de l'AC
# cle privée
openssl ecparam -genkey -name prime256v1 | openssl ec -aes256 -out private_key.pem -passin pass:toto
# cle public
﻿openssl ec -in private_key.pem -pubout -out public_key.pem
############################################################################

# faire le certificat racine
openssl req -config root-ca.cnf -x509 -sha256 -key private_key.pem -text -out ca.root.cert.pem
#############################################################################
## faire le certificat de l'association Certifplus
# certificate signing request
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=serveur" -reqexts ext -sha256 -key private_key.pem  -text -out ecc.csr.pem
# signer le certificat
openssl x509 -req -days 3650 -CA ca.root.cert.pem -CAkey private_key.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ecc.csr.pem -text -out ecc.serveur.pem
############################################################################################
# signer avec la clé privée
#﻿openssl dgst -sign private_key.pem -keyform PEM -sha256 -out signature.sign -binary filename.txt
# verifier avec la clé pub
#openssl dgst -verify public_key.pem -keyform PEM -sha256 -signature signature.sign -binary filename.txt
