#!/bin/bash -x

# création de l'AC
openssl ecparam -out private_key_ca.key.pem -name prime256v1 -genkey

# faire le certificat racine
openssl req -config root-ca.cnf -x509 -sha256 -key private_key_ca.key.pem -text -out ca.root.cert.pem

## mot de passe 'toto' pour la clé privé
# cle privée pour la signature
openssl ecparam -genkey -name prime256v1 | openssl ec -aes256 -out private_key.pem -passin pass:toto
# cle public pour la signature
﻿openssl ec -in private_key.pem -pubout -out public_key.pem
############################################################################


#############################################################################
## faire le certificat de l'association Certifplus
# certificate pour la signature
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=serveur" -reqexts ext -sha256 -key private_key.pem  -text -out ecc.csr.pem
# signer le certificat
openssl x509 -req -days 3650 -CA ca.root.cert.pem -CAkey private_key_ca.key.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ecc.csr.pem -text -out certificat_signature.pem
############################################################################################

# generer biclé pour le crtificat du serveur frontal
openssl ecparam -out private_key_serveur_frontal.key.pem -name prime256v1 -genkey
