#!/bin/bash -x

# generer la clé privé de l'AC
openssl ecparam -out ecc.ca.key.pem -name prime256v1 -genkey

# générer le certificat de l’AC
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:TRUE") -new
             -nodes -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=ACSECUTIC"
             -x509 -extensions ext -sha256 -key ecc.ca.key.pem -text -out ecc.ca.cert.pem


# faire la siganture
openssl x509 -req -days 3650 -CA ecc.ca.cert.pem -CAkey ecc.ca.key.pem
          -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE")
          -in ecc.csr.pem -text
           -out ecc.serveur.pem
