#!/bin/bash -x

# crée bi-clé
openssl ecparam -out ecc.key.pem -name prime256v1 -genkey

# Réalisez l’« auto-signature » du certificat de l’AC
openssl req -config <(printf "[req]\ndistinguished_name=dn\n[dn]\n[ext]\nbasicConstraints=CA:FALSE") -new -subj "/C=FR/L=Limoges/O=CRYPTIS/OU=SecuTIC/CN=serveur" -reqexts ext -sha256 -key ecc.key.pem -text -out ecc.csr.pem

# Crée le certificat pour le serveur  
openssl x509 -req -days 3650 -CA ecc.ca.cert.pem -CAkey ecc.ca.key.pem -CAcreateserial -extfile <(printf "basicConstraints=critical,CA:FALSE") -in ecc.csr.pem -text -out ecc.serveur.pem
